<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pyspark

In [2]:
import json

In [3]:
pyspark.HiveContext?

In [12]:
x = 321

In [13]:
s = str(x)

In [18]:
int(''.join(reversed(s)))

123

In [15]:
from math import log

In [16]:
log(2**31,10)

9.331929865583417

In [21]:
2**31-1

2147483647

In [ ]:
2147483641

In [24]:
int('0123')

123

In [22]:
-1*10

-10

In [11]:
sum = 0 
for c in s:
    print(int(c))
    sum += int(c)

print(sum)

1
2
3


ValueError: invalid literal for int() with base 10: 'a'

In [20]:
from collections import Counter

In [21]:
 nums = [4,3,2,7,8,2,3,1]

In [24]:
d = Counter(nums)

In [33]:
sorted(d.keys(), key=lambda x: d[x], reverse=True)

[3, 2, 4, 7, 8, 1]

In [39]:
list(filter(lambda x: d[x]==2, d.keys()))

[3, 2]

In [37]:
sorted(d, key=d.get, reverse=True)

[3, 2, 4, 7, 8, 1]

In [1]:
import math

In [18]:
math.log(n, 2)%1 < 1E-10

True

In [17]:
1E-1

0.1

In [10]:
math.log(536870912, 2)

29.000000000000004

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randn(5,5))

In [3]:
df

0         1         2         3         4
0 -0.929085  1.084712  0.282376  0.327175 -0.841201
1 -1.310548 -0.037599  0.273488  0.120127 -0.713031
2  0.231965 -0.383505 -0.314076 -0.580426 -0.726586
3  0.777331 -0.554692  1.238904  0.607569 -0.770279
4  1.412197 -0.221014 -0.823503  2.176565 -0.187120

In [5]:
df.columns = list(map(chr, range(97,102)))

In [6]:
df

a         b         c         d         e
0 -0.929085  1.084712  0.282376  0.327175 -0.841201
1 -1.310548 -0.037599  0.273488  0.120127 -0.713031
2  0.231965 -0.383505 -0.314076 -0.580426 -0.726586
3  0.777331 -0.554692  1.238904  0.607569 -0.770279
4  1.412197 -0.221014 -0.823503  2.176565 -0.187120

In [7]:
df.iloc[:,1:4]

b         c         d
0  1.084712  0.282376  0.327175
1 -0.037599  0.273488  0.120127
2 -0.383505 -0.314076 -0.580426
3 -0.554692  1.238904  0.607569
4 -0.221014 -0.823503  2.176565

In [10]:
df['city'] = pd.Series(["abc", "bcd", "abc", "bcd", "def"])

In [11]:
df

a         b         c         d         e city
0 -0.929085  1.084712  0.282376  0.327175 -0.841201  abc
1 -1.310548 -0.037599  0.273488  0.120127 -0.713031  bcd
2  0.231965 -0.383505 -0.314076 -0.580426 -0.726586  abc
3  0.777331 -0.554692  1.238904  0.607569 -0.770279  bcd
4  1.412197 -0.221014 -0.823503  2.176565 -0.187120  def

In [12]:
df.groupby('city').sum()

a         b         c         d         e
city                                                  
abc  -0.697120  0.701207 -0.031701 -0.253251 -1.567787
bcd  -0.533217 -0.592291  1.512392  0.727696 -1.483310
def   1.412197 -0.221014 -0.823503  2.176565 -0.187120

In [27]:
import pandas as pd
from datetime import datetime, timedelta, date

month_start = '2021-02-01'
month_end = '2021-02-28'

dates = [
    d.strftime('%F') 
    for d in pd.date_range(month_start, month_end)
]

weeks = pd.Series(pd.to_datetime(dates)).apply(
    lambda x: (x - timedelta(days=x.dayofweek))).unique()

weeks = [
    w.strftime('%F') 
    for w in pd.to_datetime(weeks)
]

In [14]:
weeks

['2021-02-01', '2021-02-08', '2021-02-15', '2021-02-22']

In [55]:
l = pd.date_range(start = find_last_thursday(month_start), end = month_end, freq='7D')\

In [56]:
l[0]

Timestamp('2021-01-28 00:00:00', freq='7D')

In [61]:
dir(l[0])

['__add__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_date_attributes',
 '_date_repr',
 '_get_date_name_field',
 '_get_start_end_field',
 '_has_time_component',
 '_repr_base',
 '_round',
 '_short_repr',
 '_time_repr',
 'asm8',
 'astimezone',
 'ceil',
 'combine',
 'ctime',
 'date',
 'day',
 'day_name',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'dst',
 'floor',
 'fold',
 'freq',
 'freqstr',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_

In [66]:
import pandas as pd
from datetime import datetime, timedelta 
def find_last_thursday(month_start: str):
    d = pd.to_datetime(month_start)
    return d - timedelta(d.dayofweek + 4)
list(pd.date_range(start = find_last_thursday(month_start), end = month_end, freq='7D')\
.to_series().apply(datetime.strftime, format= "%F"))

['2021-01-28', '2021-02-04', '2021-02-11', '2021-02-18', '2021-02-25']

In [36]:
d = pd.to_datetime(month_start)

In [37]:
d.dayofweek

0

In [39]:
d.day_name()

'Monday'

In [41]:
timedelta(4)

datetime.timedelta(days=4)

In [42]:
(d-timedelta(4)).day_name()

'Thursday'

In [47]:
base = datetime.today()
date_list = [base -timedelta(days=x) for x in range(5)]

In [48]:
date_list

[datetime.datetime(2021, 2, 11, 23, 11, 31, 83975),
 datetime.datetime(2021, 2, 10, 23, 11, 31, 83975),
 datetime.datetime(2021, 2, 9, 23, 11, 31, 83975),
 datetime.datetime(2021, 2, 8, 23, 11, 31, 83975),
 datetime.datetime(2021, 2, 7, 23, 11, 31, 83975)]

In [1]:
from collections import Counter

In [2]:
C= Counter("test")

In [4]:
d = C.copy()

In [5]:
d

Counter({'t': 2, 'e': 1, 's': 1})

In [6]:
d['t']=1

In [7]:
d

Counter({'t': 1, 'e': 1, 's': 1})

In [9]:
C

Counter({'t': 2, 'e': 1, 's': 1})

In [10]:
import numpy as np

In [12]:
a = np.zeros((2,3))

In [13]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a[0,0:2]=1

In [15]:
a

array([[1., 1., 0.],
       [0., 0., 0.]])

In [39]:
import numpy as np 

class Solution:
    def numRollsToTarget(self, d: int, f: int, target: int) -> int:
        if (d==0):
            return 0
        if target > d*f:
            return 0 
        
        ans = np.zeros((d,target))
        
        ans[0,:f]=1
        for i in range(1, d):
            for j in range(i, min((i+1)*f, target)):
                temp = 0
                for k in range(1,min(f,j)+1):
                    temp += ans[i-1,j-k]
                
                ans[i,j]= temp % (10**9+7)
                
                
        
        return ans[d-1,target-1]
            

In [40]:
a = Solution()

In [42]:
a.numRollsToTarget(30,30,500)

222616187.0

In [2]:
from collections import Counter

In [4]:
arr=[ 1,2,2,2,3,3]

In [5]:
Counter(arr)

Counter({1: 1, 2: 3, 3: 2})

In [6]:
c = _

In [7]:
c.keys()

dict_keys([1, 2, 3])

In [8]:
c.values()

dict_values([1, 3, 2])

In [9]:
len(c)

3

In [10]:
boxes="111011"

In [12]:
boxes.findall('1')

AttributeError: 'str' object has no attribute 'findall'

In [13]:
import re

In [23]:
l = []

In [24]:
for group in re.finditer("1",boxes):
    l.append(group.start(0))

In [25]:
l

[0, 1, 2, 4, 5]

In [26]:
a = np.array(l)

In [27]:
a

array([0, 1, 2, 4, 5])

In [29]:
a.tolist()

[0, 1, 2, 4, 5]

In [22]:
list(re.finditer("1",boxes))

[<re.Match object; span=(0, 1), match='1'>,
 <re.Match object; span=(1, 2), match='1'>,
 <re.Match object; span=(2, 3), match='1'>,
 <re.Match object; span=(4, 5), match='1'>,
 <re.Match object; span=(5, 6), match='1'>]

In [30]:
a= [[1,2,3],[2,3,4]]

In [31]:
b =np.array(a)

In [32]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [33]:
a

[[1, 2, 3], [2, 3, 4]]

In [34]:
type(a)

list

In [35]:
type(b)

numpy.ndarray

In [53]:
b[0,2]=4

In [37]:
b<2

array([[ True, False, False],
       [False, False, False]])

In [54]:
c =b<=3

In [55]:
c

array([[ True,  True, False],
       [ True,  True, False]])

In [42]:
c+1

array([[2, 2, 2],
       [2, 2, 1]])

In [43]:
c

array([[ True,  True,  True],
       [ True,  True, False]])

In [59]:
c[0]

array([ True,  True, False])

In [62]:
np.where(c[0,:]==0)

(array([2], dtype=int64),)

In [63]:
np.asarray(c[0]==0).nonzero()

(array([2], dtype=int64),)

In [88]:
def func(t, grid):
    N = grid.shape[0]
    bridge_builder = grid<=t
    for i in range(1,N):
        for j in range(1,N):
                bridge_builder[i,j]= (bridge_builder[i-1,j] or
                                  bridge_builder[i,j-1]) and bridge_builder[i,j]

    
    for i in range(N-2,-1,-1):
        for j in range(N-2,-1,-1):
                bridge_builder[i,j]= (bridge_builder[i,j] or bridge_builder[i+1,j] or
                                  bridge_builder[i,j+1]) and (grid[i,j]<=t)
    for i in range(1,N):
        for j in range(1,N):
            bridge_builder[i,j]= (bridge_builder[i-1,j] or
                                  bridge_builder[i,j-1]) and bridge_builder[i,j]
            
    print(bridge_builder)
    if (bridge_builder[N-1,N-1])==1:
        bridge_blocked=False
    else:
        bridge_blocked=True
    print(bridge_blocked)

In [89]:
grid = np.array([[0,1,2,3,4],[24,23,22,21,5],[12,13,14,15,16],[11,17,18,19,20],[10,9,8,7,6]])
t = 10

In [90]:
func(16,grid)

[[ True  True  True  True  True]
 [False False False False  True]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]
True


In [ ]:
def(grid, i, j):
    N = grid.shape[0]
    ans = False
    if not ans and i>0:
        if grid[i,j]<8:
            t

In [2]:
n= 100

In [11]:
d = dict().fromkeys(range(n), set())

In [13]:
d[0] =  {2,3}

In [17]:
d[0]

{2, 3, 4}

In [18]:
list(d[0])

[2, 3, 4]

In [1]:
s = "abcde"

In [2]:
t = "abcdeabcde"

In [3]:
t.find(s)

0

In [4]:
t.find('def')

-1

In [5]:
s*3

'abcdeabcdeabcde'

In [10]:
def s_test(s: str, t: str) -> bool:
    """
    given a string t, check if s= t+ .. +t an integral number of times
    """
    m = len(s)
    n = len(t)
    print(m, n, m%n, s, t*n)

    if  (m%n ==0) and (s  == t* n) :
        return True
    else:
        return False 

In [11]:
s_test("ABCABC", "ABC")

6 3 0 ABCABC ABCABCABC


False