In [1]:
s = '  '

In [2]:
s.split()

[]

In [3]:
len(_)

0

In [4]:
range(0)

range(0, 0)

In [5]:
for i in range(0):
    print(1)

In [7]:
import numpy as np

In [8]:
a= np.array(np.random.randn(10,10))

In [9]:
a

array([[-0.43918958, -1.16280901,  0.54481287, -2.19689001, -0.56636369,
        -0.00511933,  0.25318473, -1.03280164, -0.80236459,  1.13635675],
       [-0.49160359,  2.04269613,  1.62761589, -0.56623145,  1.58612237,
        -0.74358801,  1.00760651, -0.21633514, -0.6726755 , -0.70453781],
       [-2.55553365,  0.94082797, -1.55235282, -0.42448792,  0.41823496,
        -1.39117674,  2.2894294 , -0.04029071, -0.87051669,  0.85552196],
       [ 0.79470605, -0.99440579, -0.27040204, -0.30463979,  0.58833331,
        -0.97119403,  0.61863767,  0.6150953 , -1.29116947, -1.21882108],
       [ 0.15187611,  2.18145652,  0.48015237,  0.83180529, -0.07817476,
        -1.56928055,  0.67229015, -0.02217517,  1.04194525,  0.54666166],
       [ 0.48703542, -0.18584545, -0.28580765, -0.668138  ,  0.40117954,
        -1.50466058,  1.34063663,  0.56108605,  0.72067249,  1.10607223],
       [-0.06496713, -0.98978366, -1.08826802, -0.34637678, -1.15444857,
         0.51511928,  0.93348717, -0.75577443

In [10]:

type(a)

numpy.ndarray

In [12]:
a = np.array([[1,0,1],[2,1,2]])

In [13]:
a

array([[1, 0, 1],
       [2, 1, 2]])

In [15]:
b = np.array([0,1,0])

In [16]:
b

array([0, 1, 0])

In [32]:
b_upper = np.array(range(2,0,-1)).reshape(-1,1) 

In [33]:
b_upper

array([[2],
       [1]])

In [35]:
b_upper = b_upper+ b

In [39]:
new_upper = np.minimum(a,b_upper)

In [46]:
new_upper

array([[1, 0, 1],
       [1, 1, 1]])

In [40]:
b

array([0, 1, 0])

In [45]:
np.concatenate((new_upper,b.reshape(1,-1)), axis=0)

array([[1, 0, 1],
       [1, 1, 1],
       [0, 1, 0]])

In [48]:
np.minimum(new_upper[-1,:]+1,b)

array([0, 1, 0])

In [49]:
b

array([0, 1, 0])

In [51]:
(b>0).all()

False

In [52]:
c = np.array([1,1,0,1,1,1,0,1,1,1,0])

In [53]:
a

array([[1, 0, 1],
       [2, 1, 2]])

In [54]:
a[-1]

array([2, 1, 2])

In [55]:
a[-1,:]

array([2, 1, 2])

In [56]:
c

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [57]:
c

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [61]:
np.append(c,[10])

array([ 1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  0, 10])

In [62]:
c[-1]

0

In [ ]:
d=10001

In [ ]:
np.minimum(c, range(c.shape,0,-1)+d)

In [63]:
np.append(c,10)

array([ 1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  0, 10])

In [64]:
c

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [70]:
np.append(c,10)

array([ 1,  1,  0,  1,  1,  1,  0,  1,  1,  1,  0, 10])

In [71]:
range(1,0,-1)

range(1, 0, -1)

In [72]:
np.minimum(np.array([0]), range(1,0,-1))

array([0])

In [73]:
np.append(_,1)

array([0, 1])

In [74]:
c[-1]

0

In [75]:
rest = np.array(0)

In [76]:
rest.shape

()

In [77]:
type(rest)

numpy.ndarray

In [78]:
rest+2

2

In [79]:
c

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [80]:
c.argmin(c==0)

TypeError: only integer scalar arrays can be converted to a scalar index

In [85]:
np.where(c==0)

(array([ 2,  6, 10]),)

In [89]:
c.shape

(11,)

In [90]:
c[0:3]=range(2,-1,-1)

In [91]:
c

array([2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [92]:
a

array([[1, 0, 1],
       [2, 1, 2]])

In [93]:
a.shape


(2, 3)

In [94]:
m, n = a.shape

In [95]:
m

2

In [96]:
n

3

In [98]:
(a>0).all()

False